### ISSUE TITLE
Failed to decrypt password

### ISSUE THREAD

**Issue by supergarixd** [dekrypted/Fentanyl#4]
This password stealer works great its the best one i have ever used but todey i got a failed to decript in the password value 
![image](https://user-images.githubusercontent.com/97046121/206749113-e0f37cc6-f287-4d9d-b528-e60c15f3e155.png)
Do you know why does this happen?
(brave browser)

**Comment by supergarixd** [comment]
bdw i got consent to run the file :)

**Comment by supergarixd** [comment]
i figured that its not the browser (it also happens on edge and chrome)

**Comment by dekrypted** [comment]
I'm not sure why this happens. I believe it's a bug with browsers. I am doing a huge update, planned to release in a few weeks. Will be fixed by then.
