### ISSUE TITLE
explain this.

### ISSUE THREAD

**Issue by supergarixd** [dekrypted/Fentanyl#6]
i dont know a lot abt python so i might be wrong but why is this code so similar to hook stealer?
![image](https://user-images.githubusercontent.com/97046121/206928158-8828692f-0b7d-43a8-a628-6981f50901fb.png)
![image](https://user-images.githubusercontent.com/97046121/206928170-a7fd2e89-add0-4abe-9319-b14ff48e7f12.png)

**Comment by supergarixd** [comment]
yeah this is really bad

**Comment by supergarixd** [comment]
basically all the people that ran this got sent to the owner

**Comment by supergarixd** [comment]
ig enjoy all the passwords i sent you

**Comment by dekrypted** [comment]
The reason it looks so similar is because to send embeds on Discord, you have to follow a specific format **exactly.** This means two completely different stealers can have one section that looks the exact same. If you think it sends info to me, feel free to look through the code. But I can assure you only **YOU** get the information when you make a stealer.

**Comment by gimendoberilio** [comment]
That might be true, but you also send the grabbed file through the gofile api to I'm guessing, so you can also see the passwords.

If I'm wrong, then tell me why are you using the gofile api.

**Comment by dekrypted** [comment]
> That might be true, but you also send the grabbed file through the gofile api to I'm guessing, so you can also see the passwords.
> 
> If I'm wrong, then tell me why are you using the gofile api.

Gofile API doesn't let me see your passwords. Please use your brain.

I use GoFile because often the zip file is larger than Discord's 8MB max and in that case it doesn't send (Which you don't want)

GoFile has no limits.

**Comment by supergarixd** [comment]
oops man i actually used my brain and saw that it just does that if when posting the embed it returns status_code == 413 that im guessing it returns that if the file size is over 8mb and then it gives that link to me not you 🤦‍♂️.
![image](https://user-images.githubusercontent.com/97046121/207832809-16c726b1-13d0-4a49-bb77-90fe555ea4dc.png)


I am really sorry i got scared and i thought that gofile was yor server or smth like that and i was sending you my passwords i apologise for my mistake.

**Comment by dekrypted** [comment]
No worries XD
