### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by Paquitons** [dekrypted/Fentanyl#9]
whenever i use the pyinstaller --clean --onefile --key <any key> fenty.py command all i get is The system cannot find the file specified. i am new to python so i dont know how to fix this

**Comment by Reflex2909** [comment]
> whenever i use the pyinstaller --clean --onefile --key fenty.py command all i get is The system cannot find the file specified. i am new to python so i dont know how to fix this

same thing happens to me

**Comment by dekrypted** [comment]
i dont offer support for this project atm

but look at the command im sure you can figure it out
